version: "3.9"

services:
    # es:
    #     image: elasticsearch:7.17.9
    #     environment:
    #         - discovery.type=single-node
    #     ports:
    #         - "9200:9200"
    #     networks:
    #         - authors-api
    bearproject_api:
        container_name: bearproject_api
        build:
            context: .
            dockerfile: ./docker/dev/django/Dockerfile
        command: /start
        volumes:
            - .:/app:z
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        expose:
            - "8000"
        env_file:
            - ./.envs/.local/.django
            - ./.envs/.local/.postgres
        depends_on:
            - bearproject_postgres
            # - mailhog
            # - redis
            # - es
        networks:
            - backend_krakenlabs-api

    bearproject_postgres:
        container_name: bearproject_postgres
        build:
            context: .
            dockerfile: ./docker/dev/postgres/Dockerfile
        volumes:
            - dev_postgres_data:/var/lib/postgresql/data
            - dev_postgres_data_backups:/backups
        env_file:
            - ./.envs/.dev/.postgres
        networks:
            - backend_krakenlabs-api

    # mailhs-api

    # redis:
    #     image: redis:7-alpine
    #     networks:
    #         - krakenlabs-api

    # celery_worker:
    #     build:
    #         context: .
    #         dockerfile: ./docker/dev/django/Dockerfile
    #     command: /start-celeryworker
    #     volumes:
    #         - .:/app
    #     env_file:
    #         - ./.envs/.dev/.django
    #         - ./.envs/.dev/.postgres
    #     depends_on:
    #         - redis
    #         - postgres
    #         - mailhog
    #     networks:
    #         - krakenlabs-api

    # flower:
    #     build:
    #         context: .
    #         dockerfile: ./docker/dev/django/Dockerfile
    #     command: /start-flower
    #     volumes:
    #         - flower_data:/data
    #     env_file:
    #         - ./.envs/.dev/.django
    #         - ./.envs/.dev/.postgres
    #     ports:
    #         - "5555:5555"
    #     depends_on:
    #         - redis
    #         - postgres
    #     networks:
    #         - krakenlabs-api

    bearproject_nginx:
        container_name: bearproject_nginx
        restart: always
        depends_on:
            - bearproject_api
        volumes:
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        build:
            context: ./docker/local/nginx
            dockerfile: Dockerfile
        ports:
            - "8081:80"
        networks:
            - backend_krakenlabs-api

networks:
    backend_krakenlabs-api:
        external: true 

volumes:
    static_volume:
        name: bearproject_static_volume
    media_volume:
        name: bearproject_media_volume

    dev_postgres_data:
        name: bearproject_postgres_data
    dev_postgres_data_backups:
        name: bearproject_postgres_data_backups
    flower_data:
        name: bearproject_flower_data